version: '3'
services:
  client:
    build: ./client
    image: reactexpressdocker_client-image-prod
    ports:
      - 3001:3000
    container_name: react-express-client-container-prod
    depends_on:
      - server
  server:
    build: ./server
    image: reactexpressdocker_server-image-prod
    ports:
      - 5001:5000
    container_name: react-express-server-container-prod
